/*
 * Atlassian Administration API
 *
 * Atlassian Administration API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v2/orgs
// Links struct for Links
type Links struct {
	Self string `json:"self,omitempty"`
	Next string `json:"next,omitempty"`
}
