/*
 * Atlassian Administration API
 *
 * Atlassian Administration API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v2/orgs
// UserPageResponse struct for UserPageResponse
type UserPageResponse struct {
	Data []User `json:"data,omitempty"`
	Links Links `json:"links,omitempty"`
}
