/*
 * Atlassian Administration API
 *
 * Atlassian Administration API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package orgs
// UserAllOf struct for UserAllOf
type UserAllOf struct {
	// The account ID for the user. The format is a-zA-Z0-9_|-:{1,128}
	AccountId string `json:"account_id"`
	// Valid values: `atlassian`, `customer`, `app` 
	AccountType string `json:"account_type"`
	// The lifecycle status of the account  Valid values: `active`, `inactive, `closed` 
	AccountStatus string `json:"account_status"`
	// The display name of the user. Should be used for contextual rendering of the authorship in content. If the user has restricted visibility of their name, their nickname will be displayed as a substitute value 
	Name string `json:"name"`
	// The absolute URI (RFC3986) to the avatar name of the user. Should be used for contextual rendering of the authorship in content. If the user has restricted visibility of their avatar, an alternative URI will be provided as a substitute value 
	Picture string `json:"picture"`
	// The email address of the user. If the user has restricted visibility of the email address, the property will be absent 
	Email string `json:"email,omitempty"`
	// Billable status of User in Atlassian Access
	AccessBillable bool `json:"access_billable,omitempty"`
	// Last active date for a user
	LastActive string `json:"last_active,omitempty"`
}
