// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/advoretsky/atlassian-org-api/models"
)

// GetOrgIDUsersReader is a Reader for the GetOrgIDUsers structure.
type GetOrgIDUsersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOrgIDUsersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetOrgIDUsersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetOrgIDUsersBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetOrgIDUsersOK creates a GetOrgIDUsersOK with default headers values
func NewGetOrgIDUsersOK() *GetOrgIDUsersOK {
	return &GetOrgIDUsersOK{}
}

/*GetOrgIDUsersOK handles this case with default header values.

Successful operation
*/
type GetOrgIDUsersOK struct {
	Payload models.UserPage
}

func (o *GetOrgIDUsersOK) Error() string {
	return fmt.Sprintf("[GET /{orgId}/users][%d] getOrgIdUsersOK  %+v", 200, o.Payload)
}

func (o *GetOrgIDUsersOK) GetPayload() models.UserPage {
	return o.Payload
}

func (o *GetOrgIDUsersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOrgIDUsersBadRequest creates a GetOrgIDUsersBadRequest with default headers values
func NewGetOrgIDUsersBadRequest() *GetOrgIDUsersBadRequest {
	return &GetOrgIDUsersBadRequest{}
}

/*GetOrgIDUsersBadRequest handles this case with default header values.

Invalid page cursor
*/
type GetOrgIDUsersBadRequest struct {
}

func (o *GetOrgIDUsersBadRequest) Error() string {
	return fmt.Sprintf("[GET /{orgId}/users][%d] getOrgIdUsersBadRequest ", 400)
}

func (o *GetOrgIDUsersBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
