// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Links links
//
// swagger:model Links
type Links struct {

	// next
	Next string `json:"next,omitempty"`

	// self
	Self string `json:"self,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *Links) UnmarshalJSON(raw []byte) error {
	// AO0
	var dataAO0 struct {
		Next string `json:"next,omitempty"`

		Self string `json:"self,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO0); err != nil {
		return err
	}

	m.Next = dataAO0.Next

	m.Self = dataAO0.Self

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m Links) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	var dataAO0 struct {
		Next string `json:"next,omitempty"`

		Self string `json:"self,omitempty"`
	}

	dataAO0.Next = m.Next

	dataAO0.Self = m.Self

	jsonDataAO0, errAO0 := swag.WriteJSON(dataAO0)
	if errAO0 != nil {
		return nil, errAO0
	}
	_parts = append(_parts, jsonDataAO0)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this links
func (m *Links) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *Links) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Links) UnmarshalBinary(b []byte) error {
	var res Links
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
