// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UserPageResponse user page response
//
// swagger:model UserPageResponse
type UserPageResponse struct {
	UserPage

	Links
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *UserPageResponse) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 UserPage
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.UserPage = aO0

	// AO1
	var aO1 Links
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.Links = aO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m UserPageResponse) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.UserPage)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(m.Links)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this user page response
func (m *UserPageResponse) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with UserPage
	if err := m.UserPage.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with Links
	if err := m.Links.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *UserPageResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserPageResponse) UnmarshalBinary(b []byte) error {
	var res UserPageResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
